"""Pull records-added-per-year from the SciX/ADS API as a TRUE PARTITION.

Reads the token from ADS_DEV_KEY, ADS_API_KEY, or ~/.ads/dev_key. The token is
never printed. Writes _data/collection_growth.yml.

Why a partition rather than raw per-collection counts:

Raw counts overlap by 28% (they sum to 48.0M against a 37.6M corpus), so
stacking them inflates every bar. The overlap is not evenly spread either.
Measured with scripts/probe-overlap.py:

    earthscience + physics    6,464,172   the one genuinely ambiguous mass
    astronomy + planetary     1,478,244   99.9% of ALL planetary records
    astronomy + heliophysics  1,018,466   99.998% of ALL heliophysics records

So planetary and heliophysics are not siblings of astronomy, they are almost
perfect SUBSETS of it. Stacking them beside astronomy counts them twice over.

Each record is therefore assigned to exactly one collection, most specific
first, so the segments sum to the number of records actually loaded. The
earthscience/physics intersection is fetched separately so the chart can hatch
the part of the Earth science block that is also physics.

    python3 scripts/fetch-collection-growth.py
"""
import json
import os
import pathlib
import sys
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.adsabs.harvard.edu/v1/search/query"

# Most specific first. Each record falls into the first bucket it matches.
PRIORITY = ["planetary", "heliophysics", "astronomy", "earthscience", "physics", "general"]
YEARS = list(range(1993, 2027))


def token():
    for var in ("ADS_DEV_KEY", "ADS_API_KEY", "ADS_API_TOKEN"):
        if os.environ.get(var):
            return os.environ[var].strip()
    path = pathlib.Path.home() / ".ads" / "dev_key"
    if path.exists():
        return path.read_text().strip()
    sys.exit("No API token. Set ADS_API_KEY or write the key to ~/.ads/dev_key")


def count(tok, query):
    url = API + "?" + urllib.parse.urlencode({"q": query, "rows": 0})
    req = urllib.request.Request(url, headers={"Authorization": f"Bearer {tok}"})
    with urllib.request.urlopen(req, timeout=90) as r:
        return json.load(r)["response"]["numFound"]


def exclusive(collection, higher):
    """Query for a collection minus everything ranked above it."""
    q = f"collection:{collection}"
    if higher:
        q += " NOT (" + " OR ".join(f"collection:{h}" for h in higher) + ")"
    return q


def main():
    tok = token()

    total = count(tok, "*:*")
    print(f"total records {total:,}\n")

    print("current size, each record counted once, most specific label wins")
    sizes, checksum = {}, 0
    for i, c in enumerate(PRIORITY):
        sizes[c] = count(tok, exclusive(c, PRIORITY[:i]))
        checksum += sizes[c]
        print(f"  {c:<14}{sizes[c]:>12,}")
    print(f"  {'SUM':<14}{checksum:>12,}")
    print(f"  {'uncategorised':<14}{total - checksum:>12,}\n")

    print("records added per year, same partition")
    rows = []
    for y in YEARS:
        span = f"entdate:[{y}-01-01 TO {y}-12-31]"
        row = {"year": y, "all": count(tok, span)}
        for i, c in enumerate(PRIORITY):
            row[c] = count(tok, f"{span} AND ({exclusive(c, PRIORITY[:i])})")
        row["earth_physics"] = count(
            tok, f"{span} AND collection:earthscience AND collection:physics")
        rows.append(row)
        part = sum(row[c] for c in PRIORITY)
        print(f"  {y}  loaded {row['all']:>9,}  partition {part:>9,}  "
              f"earth&physics {row['earth_physics']:>8,}")

    out = pathlib.Path("_data/collection_growth.yml")
    with out.open("w") as f:
        f.write("# Generated by scripts/fetch-collection-growth.py\n")
        f.write("# Each record counted ONCE, assigned to its most specific collection.\n")
        f.write("# Priority: " + " > ".join(PRIORITY) + "\n")
        f.write("# entdate is when a record was loaded, not when it was published.\n")
        f.write(f"total: {total}\n")
        f.write("current_by_collection:\n")
        for c in PRIORITY:
            f.write(f"  {c}: {sizes[c]}\n")
        f.write("added_per_year:\n")
        for r in rows:
            f.write(f"  - year: {r['year']}\n")
            f.write(f"    all: {r['all']}\n")
            for c in PRIORITY:
                f.write(f"    {c}: {r[c]}\n")
            f.write(f"    earth_physics: {r['earth_physics']}\n")
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
